### ISSUE TITLE
Can I still sign up?

### ISSUE THREAD

**Issue by jhalaa** [freeCodeCamp/2018-jamstack-hackathon#1]
The sign up link in the Readme page looks like it is broken. Am I too late to sign up ?

**Comment by juzQrios** [comment]
I'm not sure if the Signups are closed but do try applying [here](https://freecodecamp.typeform.com/to/v4mc19)

**Comment by dunphyben** [comment]
Hi Jhalaa, there is no sign up link in the readme. If you successfully applied for a ticket then you were sent one. Registration is now closed.
